import type { CertificationScheme } from './types';

export const schemesData: CertificationScheme[] = [
  {
    id: 'skema-01',
    title: 'Trainee Kasir',
    description: 'Sertifikasi kompetensi untuk operasional kasir di industri ritel modern.',
    units: [
      { code: 'G.46RIT00.001.1', name: 'Merapihkan Area Kerja' },
      { code: 'G.46RIT00.002.1', name: 'Menjalankan Tugas dan Tanggung Jawab Pribadi' },
      { code: 'G.46RIT00.003.1', name: 'Mengoperasikan Peralatan Dasar Ritel' },
      { code: 'G.46RIT00.004.1', name: 'Membangun Perilaku Kerja Ritel yang Efektif' },
      { code: 'G.46RIT00.005.1', name: 'Melakukan Pengemasan Barang Dagang' },
      { code: 'G.46RIT00.006.1', name: 'Melakukan Penerimaan Barang Dagangan (Receiving)' },
      { code: 'G.46RIT00.008.1', name: 'Berkomunikasi Aktif dalam Lingkungan Kerja Ritel' },
      { code: 'G.46RIT00.009.1', name: 'Berinteraksi Aktif dalam Membantu Pelanggan Berbelanja' },
      { code: 'G.46RIT00.014.1', name: 'Menjual Produk dan Layanan Ritel' },
      { code: 'G.46RIT00.018.1', name: 'Menerapkan Perilaku Kerja Aman di Gerai Ritel' },
    ]
  },
  {
    id: 'skema-02',
    title: 'Pramuniaga',
    description: 'Sertifikasi kompetensi untuk pramuniaga yang terampil dalam pelayanan pelanggan dan penataan produk.',
    units: [
        { code: 'G.46RIT00.001.1', name: 'Merapihkan Area Kerja' },
        { code: 'G.46RIT00.002.1', name: 'Menjalankan Tugas dan Tanggung Jawab Pribadi' },
        { code: 'G.46RIT00.003.1', name: 'Mengoperasikan Peralatan Dasar Ritel' },
        { code: 'G.46RIT00.004.1', name: 'Membangun Perilaku Kerja Ritel yang Efektif' },
        { code: 'G.46RIT00.005.1', name: 'Melakukan Pengemasan Barang Dagang' },
        { code: 'G.46RIT00.008.1', name: 'Berkomunikasi Aktif dalam Lingkungan Kerja Ritel' },
        { code: 'G.46RIT00.018.1', name: 'Menerapkan Perilaku Kerja Aman di Gerai Ritel' },
        { code: 'G.46RIT00.026.1', name: 'Membantu Pelaksanaan Perhitungan Stok Barang Dagangan' },
        { code: 'G.46RIT00.031.1', name: 'Melakukan Kegiatan Pemajangan Barang Dagangan (Display)' },
    ]
  },
  {
    id: 'skema-03',
    title: 'Bellboy',
    description: 'Sertifikasi kompetensi untuk jasa porter profesional di industri perhotelan.',
    units: [
        { code: 'I.55HDR00.006.2', name: 'Melakukan Komunikasi Melalui Telepon' },
        { code: 'I.55HDR00.009.2', name: 'Menyediakan Jasa Porter' },
        { code: 'I.55HDR00.149.2', name: 'Melakukan Kerjasama Dengan Kolega dan Pelanggan' },
        { code: 'I.55HDR00.150.2', name: 'Melakukan Kerja Dalam Lingkungan Sosial yang Beragam' },
        { code: 'I.55HDR00.151.2', name: 'Mengikuti Prosedur Kesehatan, Keselamatan dan Keamanan di Tempat Kerja' },
        { code: 'I.55HDR00.152.2', name: 'Mengembangkan Pengetahuan tentang Industri Perhotelan' },
        { code: 'I.55HDR00.153.2', name: 'Memperbaharui Pengetahuan Lokal' },
        { code: 'I.55HDR00.155.2', name: 'Menangani Situasi Konflik' },
        { code: 'I.55HDR00.161.2', name: 'Mengikuti Prosedur Kebersihan di Tempat Kerja' },
        { code: 'I.55HDR00.163.2', name: 'Menyediakan Pertolongan Pertama' },
        { code: 'I.55HDR00.164.2', name: 'Melaksanakan Prosedur Administrasi' },
        { code: 'I.55HDR00.206.2', name: 'Memulai Percakapan dan Mengembangkan Hubungan Baik dengan Tamu' },
        { code: 'I.55HDR00.207.2', name: 'Melakukan Percakapan Singkat di Telepon' },
        { code: 'I.55HDR00.212.2', name: 'Membaca Teks Informasi' },
        { code: 'I.55HDR00.213.2', name: 'Menulis Pesan Singkat' },
        { code: 'I.55HDR00.217.2', name: 'Berkomunikasi Secara Lisan Dalam Bahasa Inggris pada Tingkat Operasional Dasar' },
        { code: 'I.55HDR00.218.2', name: 'Melakukan Tugas Perlindungan Anak yang Relevan dengan Industri Pariwisata' },
        { code: 'I.55HDR00.229.2', name: 'Membangun dan Memelihara Tempat Kerja yang Aman' },
        { code: 'I.55HDR00.244.2', name: 'Menjaga Keamanan Lingkungan Kerja dan Harta Benda' },
        { code: 'I.55HDR00.248.2', name: 'Menjelaskan Fasilitas dan Pelayanan Hotel' },
        { code: 'I.55HDR00.250.2', name: 'Mencari dan Mendapatkan Data Komputer' },
        { code: 'I.55HDR00.154.2', name: 'Mempromosikan Produk dan Jasa Kepada Pelanggan' },
    ]
  },
  {
    id: 'skema-04',
    title: 'Reservation Staff',
    description: 'Sertifikasi kompetensi untuk staf reservasi yang menangani pemesanan di industri perhotelan.',
    units: [
        { code: 'I.55HDR00.001.2', name: 'Memproses Reservasi' },
        { code: 'I.55HDR00.006.2', name: 'Melakukan Komunikasi Melalui Telepon' },
        { code: 'I.55HDR00.149.2', name: 'Melakukan Kerjasama Dengan Kolega dan Pelanggan' },
        { code: 'I.55HDR00.150.2', name: 'Melakukan Kerja Dalam Lingkungan Sosial yang Beragam' },
        { code: 'I.55HDR00.151.2', name: 'Mengikuti Prosedur Kesehatan, Keselamatan dan Keamanan di Tempat Kerja' },
        { code: 'I.55HDR00.152.2', name: 'Mengembangkan Pengetahuan tentang Industri Perhotelan' },
        { code: 'I.55HDR00.155.2', name: 'Menangani Situasi Konflik' },
        { code: 'I.55HDR00.163.2', name: 'Menyediakan Pertolongan Pertama' },
        { code: 'I.55HDR00.164.2', name: 'Melaksanakan Prosedur Administrasi' },
        { code: 'I.55HDR00.166.2', name: 'Menyiapkan Dokumen Bisnis' },
        { code: 'I.55HDR00.175.2', name: 'Membuat Dokumen di Dalam Komputer' },
        { code: 'I.55HDR00.176.2', name: 'Merancang Dokumen, Laporan dan Lembar Kerja Pada Komputer' },
        { code: 'I.55HDR00.206.2', name: 'Memulai Percakapan dan Mengembangkan Hubungan Baik dengan Tamu' },
        { code: 'I.55HDR00.207.2', name: 'Melakukan Percakapan Singkat di Telepon' },
        { code: 'I.55HDR00.208.2', name: 'Menggunakan Bahasa Lisan untuk Negosiasi Pertukaran Informasi yang Kompleks Dalam Jenis Konteks Hotel dan Restoran' },
        { code: 'I.55HDR00.217.2', name: 'Berkomunikasi Secara Lisan Dalam Bahasa Inggris pada Tingkat Operasional Dasar' },
        { code: 'I.55HDR00.218.2', name: 'Melakukan Tugas Perlindungan Anak yang Relevan dengan Industri Pariwisata' },
        { code: 'I.55HDR00.226.2', name: 'Bekerja Secara Kooperatif Dalam Lingkungan Administrasi Umum' },
        { code: 'I.55HDR00.229.2', name: 'Membangun dan Memelihara Tempat Kerja yang Aman' },
        { code: 'I.55HDR00.230.2', name: 'Membaca Bahasa Inggris tingkat Lanjut' },
        { code: 'I.55HDR00.247.2', name: 'Memberikan Petunjuk tentang Lokasi' },
        { code: 'I.55HDR00.248.2', name: 'Menjelaskan Fasilitas dan Pelayanan Hotel' },
        { code: 'I.55HDR00.250.2', name: 'Mencari dan Mendapatkan Data Komputer' },
        { code: 'I.55HDR00.255.2', name: 'Mengoperasikan Sistem Reservasi Komputer' },
        { code: 'I.55HDR00.154.2', name: 'Mempromosikan Produk dan Jasa Kepada Pelanggan' },
        { code: 'I.55HDR00.165.2', name: 'Menyajikan Informasi' },
    ]
  },
  {
    id: 'skema-05',
    title: 'Asisten Kamera 2',
    description: 'Sertifikasi kompetensi dasar untuk asisten kamera dalam produksi audio-visual.',
    units: [
        { code: 'R.90CAM00.001.1', name: 'Mengikuti Prosedur Kesehatan, Keselamatan, dan Keamanan di Tempat Kerja' },
        { code: 'R.90CAM00.002.1', name: 'Menerapkan Etika, Tata Krama, dan Tanggung Jawab Profesi' },
        { code: 'R.90CAM00.012.1', name: 'Menggunakan Slate pada saat Syuting' },
        { code: 'R.90CAM00.014.1', name: 'Mendistribusikan Data File Digital' },
        { code: 'R.90PRO00.001.1', name: 'Mengoperasikan Perangkat Lunak untuk Manajemen Produksi' },
    ]
  },
  {
    id: 'skema-06',
    title: 'Content Creator Junior',
    description: 'Sertifikasi kompetensi untuk pembuatan konten multimedia dasar, dari riset hingga integrasi komponen.',
    units: [
        { code: 'J.59MTM00.002.1', name: 'Melakukan Riset Kreatif Multimedia' },
        { code: 'J.59MTM00.004.1', name: 'Menyusun Creative Brief' },
        { code: 'J.59MTM00.011.1', name: 'Membuat Aset Visual Berdasarkan Langkah Kerja yang Telah Ditetapkan' },
        { code: 'J.59MTM00.015.1', name: 'Membuat Aset Audio Berdasarkan Langkah Kerja Yang Telah Ditetapkan' },
        { code: 'J.59MTM00.018.1', name: 'Mengintegrasikan Seluruh Komponen Multimedia Terkait Audio dan Visual' },
    ]
  },
  {
    id: 'skema-07',
    title: 'Trainee Store Administration',
    description: 'Sertifikasi kompetensi untuk tugas-tugas administratif pendukung di toko ritel.',
    units: [
        { code: 'G.46RIT00.001.1', name: 'Merapihkan Area Kerja' },
        { code: 'G.46RIT00.002.1', name: 'Menjalankan Tugas dan Tanggung Jawab Pribadi' },
        { code: 'G.46RIT00.003.1', name: 'Mengoperasikan Peralatan Dasar Ritel' },
        { code: 'G.46RIT00.004.1', name: 'Membangun Perilaku Kerja Ritel yang Efektif' },
        { code: 'G.46RIT00.006.1', name: 'Melakukan Penerimaan Barang Dagangan (Receiving)' },
        { code: 'G.46RIT00.007.1', name: 'Melakukan Pekerjaan Pendukung Administratif Ritel' },
        { code: 'G.46RIT00.008.1', name: 'Berkomunikasi Aktif dalam Lingkungan Kerja Ritel' },
        { code: 'G.46RIT00.009.1', name: 'Berinteraksi Aktif dalam Membantu Pelanggan Berbelanja' },
        { code: 'G.46RIT00.018.1', name: 'Menerapkan Perilaku Kerja Aman di Gerai Ritel' },
        { code: 'G.46RIT00.026.1', name: 'Membantu Pelaksanaan Perhitungan Stok Barang Dagangan' },
    ]
  },
  {
    id: 'skema-08',
    title: 'Skema Sertifikasi Kualifikasi II Teknisi Akuntansi Yunior',
    description: 'Sertifikasi kualifikasi II KKNI untuk teknisi akuntansi level yunior.',
    units: [
        { code: 'M.692000.001.02', name: 'Menerapkan Prinsip Praktik Profesional dalam Bekerja' },
        { code: 'M.692000.002.02', name: 'Menerapkan Praktik- Praktik Kesehatan dan Keselamatan di Tempat Kerja' },
        { code: 'M.692000.007.02', name: 'Memproses Entry Jurnal' },
        { code: 'M.692000.008.02', name: 'Memproses Buku Besar' },
        { code: 'M.692000.013.02', name: 'Menyusun Laporan Keuangan' },
        { code: 'M.692000.022.02', name: 'Mengoperasikan Paket Program Pengolah Angka/Spreadsheet' },
        { code: 'M.692000.023.02', name: 'Mengoperasikan Aplikasi Komputer Akuntansi' },
    ]
  },
  {
    id: 'skema-09',
    title: 'Skema Sertifikasi KKNI Level II Pada Kompetensi Keahlian Akuntansi dan Keuangan Lembaga',
    description: 'Sertifikasi KKNI Level II untuk bidang keahlian Akuntansi dan Keuangan Lembaga.',
    units: [
        { code: 'M.692000.001.02', name: 'Menerapkan Prinsip Praktik Profesional dalam Bekerja' },
        { code: 'M.692000.002.02', name: 'Menerapkan Praktik- Praktik Kesehatan dan Keselamatan di Tempat Kerja' },
        { code: 'M.692000.007.02', name: 'Memproses Entry Jurnal' },
        { code: 'M.692000.008.02', name: 'Memproses Buku Besar' },
        { code: 'M.692000.013.02', name: 'Menyusun Laporan Keuangan' },
        { code: 'M.692000.022.02', name: 'Mengoperasikan Paket Program Pengolah Angka/Spreadsheet' },
        { code: 'M.692000.023.02', name: 'Mengoperasikan Aplikasi Komputer Akuntansi' },
    ]
  },
  {
    id: 'skema-10',
    title: 'Asisten Editor 2',
    description: 'Sertifikasi kompetensi dasar untuk asisten editor dalam pasca-produksi audio-visual.',
    units: [
        { code: 'R.90CAM00.001.1', name: 'Mengikuti Prosedur Kesehatan, Keselamatan, dan Keamanan di Tempat Kerja' },
        { code: 'R.90CAM00.002.1', name: 'Menerapkan Etika, Tata Krama, dan Tanggung Jawab Profesi' },
        { code: 'R.90CUT00.006.2', name: 'Melakukan Administrasi Materi Hasil Syuting' },
        { code: 'R.90CUT00.007.1', name: 'Memastikan Kelengkapan Editing' },
        { code: 'R.90CUT00.009.1', name: 'Mendokumentasikan Hasil Klasifikasi Materi Syuting' },
    ]
  },
  {
    id: 'skema-11',
    title: 'Public Area Cleaner',
    description: 'Sertifikasi kompetensi untuk petugas kebersihan area publik di industri perhotelan.',
    units: [
        { code: 'I.55HDR00.005.2', name: 'Melaksanakan Prosedur Klerikal' },
        { code: 'I.55HDR00.011.2', name: 'Membersihkan Lokasi/Area dan Peralatan' },
        { code: 'I.55HDR00.149.2', name: 'Melakukan Kerjasama Dengan Kolega dan Pelanggan' },
        { code: 'I.55HDR00.150.2', name: 'Melakukan Kerja Dalam Lingkungan Sosial yang Beragam' },
        { code: 'I.55HDR00.151.2', name: 'Mengikuti Prosedur Kesehatan, Keselamatan dan Keamanan di Tempat Kerja' },
        { code: 'I.55HDR00.152.2', name: 'Mengembangkan Pengetahuan tentang Industri Perhotelan' },
        { code: 'I.55HDR00.155.2', name: 'Menangani Situasi Konflik' },
        { code: 'I.55HDR00.161.2', name: 'Mengikuti Prosedur Kebersihan di Tempat Kerja' },
        { code: 'I.55HDR00.162.2', name: 'Membersihkan Tempat dan Peralatan Kerja' },
        { code: 'I.55HDR00.163.2', name: 'Menyediakan Pertolongan Pertama' },
        { code: 'I.55HDR00.164.2', name: 'Melaksanakan Prosedur Administrasi' },
        { code: 'I.55HDR00.168.2', name: 'Menerima dan Menyimpan Barang' },
        { code: 'I.55HDR00.206.2', name: 'Memulai Percakapan dan Mengembangkan Hubungan Baik dengan Tamu' },
        { code: 'I.55HDR00.209.2', name: 'Menangani Keluhan' },
        { code: 'I.55HDR00.213.2', name: 'Menulis Pesan Singkat' },
        { code: 'I.55HDR00.217.2', name: 'Berkomunikasi Secara Lisan Dalam Bahasa Inggris pada Tingkat Operasional Dasar' },
        { code: 'I.55HDR00.218.2', name: 'Melakukan Tugas Perlindungan Anak yang Relevan dengan Industri Pariwisata' },
        { code: 'I.55HDR00.229.2', name: 'Membangun dan Memelihara Tempat Kerja yang Aman' },
        { code: 'I.55HDR00.248.2', name: 'Menjelaskan Fasilitas dan Pelayanan Hotel' },
        { code: 'I.55HDR00.260.2', name: 'Menjaga Keselamatan di Lokasi Personel' },
        { code: 'I.55HDR00.154.2', name: 'Mempromosikan Produk dan Jasa Kepada Pelanggan' },
    ]
  },
  {
    id: 'skema-12',
    title: 'Room Attendant',
    description: 'Sertifikasi kompetensi untuk petugas housekeeping yang bertanggung jawab atas kebersihan kamar tamu.',
    units: [
        { code: 'I.55HDR00.005.2', name: 'Melaksanakan Prosedur Klerikal' },
        { code: 'I.55HDR00.010.2', name: 'Menyediakan Layanan Housekeeping untuk Tamu' },
        { code: 'I.55HDR00.011.2', name: 'Membersihkan Lokasi/Area dan Peralatan' },
        { code: 'I.55HDR00.012.2', name: 'Menyiapkan Kamar untuk Tamu' },
        { code: 'I.55HDR00.016.2', name: 'Menyediakan Layanan Turn Down' },
        { code: 'I.55HDR00.020.2', name: 'Menyediakan Layanan Room Butler' },
        { code: 'I.55HDR00.149.2', name: 'Melakukan Kerjasama Dengan Kolega dan Pelanggan' },
        { code: 'I.55HDR00.150.2', name: 'Melakukan Kerja Dalam Lingkungan Sosial yang Beragam' },
        { code: 'I.55HDR00.151.2', name: 'Mengikuti Prosedur Kesehatan, Keselamatan dan Keamanan di Tempat Kerja' },
        { code: 'I.55HDR00.152.2', name: 'Mengembangkan Pengetahuan tentang Industri Perhotelan' },
        { code: 'I.55HDR00.155.2', name: 'Menangani Situasi Konflik' },
        { code: 'I.55HDR00.161.2', name: 'Mengikuti Prosedur Kebersihan di Tempat Kerja' },
        { code: 'I.55HDR00.162.2', name: 'Membersihkan Tempat dan Peralatan Kerja' },
        { code: 'I.55HDR00.163.2', name: 'Menyediakan Pertolongan Pertama' },
        { code: 'I.55HDR00.164.2', name: 'Melaksanakan Prosedur Administrasi' },
        { code: 'I.55HDR00.187.2', name: 'Membangun Tempat Kerja yang Aman' },
        { code: 'I.55HDR00.206.2', name: 'Memulai Percakapan dan Mengembangkan Hubungan Baik dengan Tamu' },
        { code: 'I.55HDR00.209.2', name: 'Menangani Keluhan' },
        { code: 'I.55HDR00.211.2', name: 'Membaca Instruksi dan Diagram Dalam Konteks yang Berkaitan' },
        { code: 'I.55HDR00.217.2', name: 'Berkomunikasi Secara Lisan Dalam Bahasa Inggris pada Tingkat Operasional Dasar' },
        { code: 'I.55HDR00.218.2', name: 'Melakukan Tugas Perlindungan Anak yang Relevan dengan Industri Pariwisata' },
        { code: 'I.55HDR00.226.2', name: 'Bekerja Secara Kooperatif Dalam Lingkungan Administrasi Umum' },
        { code: 'I.55HDR00.243.2', name: 'Menyediakan Fasilitas Kehilangan dan Penemuan' },
        { code: 'I.55HDR00.244.2', name: 'Menjaga Keamanan Lingkungan Kerja dan Harta Benda' },
        { code: 'I.55HDR00.250.2', name: 'Mencari dan Mendapatkan Data Komputer' },
        { code: 'I.55HDR00.154.2', name: 'Mempromosikan Produk dan Jasa Kepada Pelanggan' },
    ]
  },
];